networks:
  default:
    external:
      name: proxy

services:
  ipfs:
    restart: unless-stopped
    image: ipfs/go-ipfs:v0.18.1
    volumes:
      - "/home/live/ipfs:/data/ipfs"
    ports:
      - "4001:4001"
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=ipfs.benderfactory.com
      - LETSENCRYPT_HOST=ipfs.benderfactory.com
      - VIRTUAL_PORT=8080
